version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    container_name: node-backend
  frontend:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    container_name: nginx-frontend
